### ISSUE TITLE
Nicer way to write filters?

### ISSUE THREAD

**Issue by sanpoChew** [directus/directus-sdk-javascript#1]
So I got this working by looking at how the php is structured and carrying it over into objects, it's pretty verbose though:

```
const pages = await directus.getItems('pages', {
      filters: {
        show_in_navbar: {
          '=': 1,
        },
      },
    });
```

any better ways to do it?

Thanks,

**Comment by WellingGuzman** [comment]
Hey @sanpoChew, do you have any suggestion?

**Comment by sanpoChew** [comment]
Hi @WellingGuzman I wasn't really suggesting changing something if this is how it's meant to work, just that there's no javascript example in the [docs](https://api.getdirectus.com/1.1/#API_Endpoints) so I thought I might be missing something. 

Looking back at it I think it was just having the symbol as a key that was rubbing me the wrong way and after changing it to eq or just omitting the object altogether it looks much nicer

```
const pages = await directus.getItems('pages', {
      filters: {
        show_in_navbar: 1
      },
    });
```

just as an aside, I can't seem to get the columns parameter to work, is there something I am doing wrong?

```
    const pages = await directus.getItems('pages', {
      order: {
        name: 'ASC',
      },
      columns: 'name',
      filters: {
        show_in_navbar: 1,
      },
    });
```

Thanks,

**Comment by RijkvanZanten** [comment]
Are you using API version 1.1? The columns param is only available in that version.

**Comment by sanpoChew** [comment]
Yeah I'm using 1.1, I've specified it when initializing the SDK like the example in the README, everything else I have tried seems to work perfectly it's just columns. It doesn't error or anything so I guess it's just getting ignored for some reason

**Comment by RijkvanZanten** [comment]
@sanpoChew @WellingGuzman It seems like this is an issue in the Directus API itself instead of the JavaScript SDK. I've just tried out the param on a fresh installation on the development branch (with api 1.1) and it gets ignored there as well. 

`http://local.directus:8888/api/1.1/tables/test/rows?columns=title`

**Comment by WellingGuzman** [comment]
Yes, this is an API issue, I will fix this, @sanpoChew thanks for reporting this. You don't have to open another ticket.
