### ISSUE TITLE
errors in react-native

### ISSUE THREAD

**Issue by newah** [directus/directus-sdk-javascript#10]
Using directus-sdk-javascript with react native gives errors as it's using "request" module for executing requests which has dependencies on crypto and tls. These aren't natively supported in react-native.

request module could be replaced with fetch.

**Comment by rijkvanzanten** [comment]
Hi @newah, thanks for reaching out!

Are you referring to the browser-native `Fetch` API or [the fetch package](https://www.npmjs.com/package/fetch)?

Unfortunately, browser-native Fetch isn't available in Node. Do you know of any request package which supports all three target? (Node, browser & RN).

**Comment by newah** [comment]
fetch for reactnative https://facebook.github.io/react-native/docs/network.html . Yes, it doesn't support other platforms. 

It's only the "performRequest" inside base.js that's using "const request = require('request');"
So maybe we could add dynamic calling based on platform/technology and still use request for browser, but fetch for RN?

**Comment by rijkvanzanten** [comment]
That sounds like a nice solution! We could also replace the request library in favor of a more compatible one all together. It seems like RN supports XMLHttpRequest / Fetch and that it should work with something like [axios](https://github.com/mzabriskie/axios). That way we don't have to perform platform checks 😃

**Comment by newah** [comment]
Actually I even started switching request to axios in base.js. But couldn't pass access token (bearer auth header) nicely. Problems with authentication persist only on iOS.

I saw https://www.npmjs.com/package/react-native-axios - react native words and though these are different axios implementations. But apparently they're the same ;)

So yeah, this should be a perfect solution if passing bearer works nicely.

**Comment by rijkvanzanten** [comment]
Hmm, we could also use the `access_token` url param instead of the bearer token if that makes implementing axios a little easier?

**Comment by newah** [comment]
That makes it easy. But would need to check if there're no problems with other params.

Also, probably can't/shouldn't pass it as url param for post? :)

**Comment by rijkvanzanten** [comment]
Great question! I believe the auth param is available on all endpoints, but that's something we'd have to test 👍

**Comment by newah** [comment]
I'll try axios again when I have some time. Maybe I missed something as thing like this would make a shit-storm of complaints ;)

**Comment by rijkvanzanten** [comment]
Please let me know how it goes! And feel free to open up a PR if you have a fix 😄

**Comment by rijkvanzanten** [comment]
@newah I've pushed a new version which replaces `request` with `axios`. Could you try out the beta version of `v2.0.0` by running `npm install directus-sdk-javascript@beta`?

Let me know if that fixes the RN problems 😃

**Comment by newah** [comment]
@rijkvanzanten pretty amazing ;) that works exactly as expected! Will test with filtering and all soon :)

Thanks!

There's a missed comma in tutorial:
const client = new RemoteInstance({
  url: 'http://instance.directus.io/api/1.1/'**,**   <------ this comma is missing
  accessToken: [user-token] // optional, can be used without on public routes
});

**Comment by rijkvanzanten** [comment]
Great catch! I'll fix that in a minute. Please let us know if you run into any other problems 😄
