### ISSUE TITLE
Error with Client-side SDK with getItem

### ISSUE THREAD

**Issue by ohmfox** [directus/directus-sdk-javascript#11]
I've got the SDK set up on the client side and I have an API key set up like so:

```
const client = new SDK(
  'API_KEY_IS_HERE',
  'https://clients.byfrost.io/api', // Directus-hosted or own server 
  1.1 // API Version 
)
```

If I access the API from my browser, while logged in it works. It could be something related to CORS - it looks like it is having a problem with the OPTIONS request initially.

Let me know if you need more info! Thanks!

**Comment by WellingGuzman** [comment]
Hey @ohmfox, did you enable CORS in the `configuration.php` file?

**Comment by ohmfox** [comment]
Hey @WellingGuzman,

We just did. We are now getting this error:

```Fetch API cannot load https://clients.byfrost.io/api/1.1/tables/IfBattery_Home/rows/1. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://30f11f27.ngrok.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

Looking to see if it is on our end or not.

**Comment by ohmfox** [comment]
Also, might be worth mentioning we are using the docker build for this. We might have an error there. Checking it out.

**Comment by ohmfox** [comment]
Just fixed it! Thanks for the help!

**Comment by WellingGuzman** [comment]
Hey @ohmfox, glad that you solve the problem, could you care in share what happened and how you solve it, for our future generations? :)

**Comment by ohmfox** [comment]
We had to add CORS Headers to the Nginx reverse proxy we had the server running behind.
