### ISSUE TITLE
getUsers and getUser is missing

### ISSUE THREAD

**Issue by simonmilz** [directus/directus-sdk-javascript#14]
Those two endpoints are missing, see: https://api.getdirectus.com/1.1/#Getting_Data

**Comment by WellingGuzman** [comment]
Thanks for pointing it out @simonmilz,

We will add them soon, and it will be included in the next release `2.0.1`

**Comment by rijkvanzanten** [comment]
These endpoints are only available in the PHP SDK at the moment. The JS SDK provides methods for every API URL endpoint and there isn't a specific endpoint for getting users.

It is currently possible to retrieve the users by using `getItems('directus_users')`

I could add it as a convenience method though. Thoughts @WellingGuzman?

**Comment by WellingGuzman** [comment]
This was closed by https://github.com/directus/directus-sdk-javascript/commit/b073590b30b4e9f43016adc22ac0bd0c473f42ef
