### ISSUE TITLE
Creating wrong UR:  api/1.1/tables/tables/wp_posts/rows/rows

### ISSUE THREAD

**Issue by kauaicreative** [directus/directus-sdk-javascript#16]
```js
const RemoteInstance = require('directus-sdk-javascript/remote')
const client = new RemoteInstance({
    url: 'http://directus2.dev/api/1.1/'
})
     
 client.getItems('tables/wp_posts/rows')
        .then(res => console.log(res))
        .catch(err => console.log(err))
```

returns 404 (Not Found)
http://directus2.dev/api/1.1/tables/tables/wp_posts/rows/rows

The output should read 
http://directus2.dev/api/1.1/tables/wp_posts/rows

Is this a bug or am I doing something wrong?

Thanks.

**Comment by rijkvanzanten** [comment]
Hi @kauaicreative! Just entering the table name is enough for this method. It adds the tables/ and /rows for you 👍🏻

**Comment by kauaicreative** [comment]
Thanks that makes sense - I see all the properties now.
