### ISSUE TITLE
getUser does not accept double-digit parameters as id

### ISSUE THREAD

**Issue by dhardenbicker** [directus/directus-sdk-javascript#17]
getUser does not accept double-digit parameters with Directus Api 1.1 and Directus 6.4.0.

eg. "https://localhost/directus/api/1/users/24" gets Error 404

Instead of
```javascript
getUser (id = required) Param ('id')) {
return this._get (`users/${id}`);
}
```
the users path should be:
```javascript
getUser (id = requiredParam ('id')) {
    return this._get (`users/?id=${id}`);
}
```

in Browser:
"https://localhost/directus/api/1/users/?id=24"

Successfully tested with react native app.

**Comment by WellingGuzman** [comment]
Hey @dhardenbicker, thanks for reporting this.

This is an issue on the API, we've fixed and it will be release in the next version (6.4.3)

Closed by https://github.com/directus/directus/commit/58c946a760281a44264a9d5a17fd2d1028932140

**Comment by rijkvanzanten** [comment]
And make sure to use API version 1.1 instead of 1, as it's more stable and has a richer feature set 🙂
