### ISSUE TITLE
Possible need to refactor promises

### ISSUE THREAD

**Issue by HauntedSmores** [directus/directus-sdk-javascript#2]
By using deferred and the way bundling is queued, you get some unexpected behavior in Angular 2.

Data gets loaded from the server just fine, but does not render in the view until you make an action (click something) and "wake up" the view. According to people on the Angular 2 team, this is commonly a problem with SDK's and third party libraries and their bundling order/shipping their own polyfills/or generally doing something odd with promises.

Not sure if this is super specific to Angular 2, but figured it would be good for you guys to be aware of.

**Comment by RijkvanZanten** [comment]
Could you provide us with an actual Angular implementation example which results in this quirky behavior?

**Comment by rijkvanzanten** [comment]
I wasn't able to reproduce this issue, but the way the api uses promises is going to be overhauled in `2.0.0`
