### ISSUE TITLE
Add an authentication method

### ISSUE THREAD

**Issue by Alekshar** [directus/directus-sdk-javascript#20]
While using the SDK I frequently have to get by my self the access token.

So I am wondering if there is any reason why there is no method in the SDK to get the token ? 
If none, I'll be happy to try a pull request for this.

**Comment by rijkvanzanten** [comment]
Good one! There's no real reason that it isn't included, other than the SDK expects an access token on initialization so it can use it for further requests.

If we implement the method to request the access token, I guess we also need a method to save the newly fetched access token to the SDK object for further requests. What are your thoughts on this?

We'd love to see a PR for this 😄
