### ISSUE TITLE
Adding a License to this repo

### ISSUE THREAD

**Issue by skadimoolam** [directus/directus-sdk-javascript#24]
Hi,
I kindly request directus team to add a License to this repo. This has not been an issue for me thus far as I have used directus-sdk-javascript for personal projects. I am thinking of using this library for a client project  where licenses become an issue.

Thanks

**Comment by rijkvanzanten** [comment]
Hey @skadimoolam!

There is a license in this repo?
https://github.com/directus/directus-sdk-javascript/blob/master/LICENSE

Let me know if I understand your request wrong.

✌🏻
