### ISSUE TITLE
deleteBulk does not work

### ISSUE THREAD

**Issue by Padle** [directus/directus-sdk-javascript#28]
Hi all.
I am currently working on a project with Directus as backend and using this sdk in my current Node.js project. Some of the data in my database must be updated daily. 
Since checking all data would be too time-consuming, all data will be replaced every time with the help of the api. I am using the sdk to read all data of a table, save the IDs, delete all data of the table with the help of it and insert the new records. This works all fine expect the delete-function.

I tried to use `deleteBulk()` on my table but the function doesn't seem to work.

## Expected Behavior
I retrieve all data from the database with the help of `client.getItems('table_name')`, iterate over the received data and store all IDs in an array. This array is then passed to the function `client.deleteBulk('table_name', array)` to delete all data of the table.

For Example:
```javascript
var arrayIds = []; 
client.getItems('table_name')
.then( function (entries) {
        entries.data.foreach( function(entry) {
                 arrayIds.push( { "id": entry.id });
        });
});

client.deleteBulk('table_name', arrayIds);
```
The output from the array looks like this: `[{id: 1}, {id: 2}]`
It is the same as shown in the [api documentation](https://api.getdirectus.com/1.1/#Batch_Delete_Items).
I now expect all data of the table with this ids to be deleted, but this is not the case.
## Current Behavior
The current behavior is an error message like this: 
> {  success: false,
>    error: { message: 'Rows no specified' },
>    code: 0,
>    class: 'Exception',
>    file: '/var/www/html/directus/api/routes/A1/Entries.php',
>    line: 64  }
## Possible Solution
I tested the problem with POSTMAN, but it was working all right.
Send: 
> { "rows": [ {"id": 1}, {"id": 2} ] }

Response:
> { "meta": { "table": "table_name", "ids": [ 1, 2 ] }, "data": { "success": true } }

The problem lies in the source code.
The function [deleteBulk()](https://github.com/directus/directus-sdk-javascript/blob/3eec38753d6f56aee57eabc3e419f1541898c5a8/remote.js#L154-L162) requires two parameter: the table name and all ids in an array like above. They are then passed to the [_delete() ](https://github.com/directus/directus-sdk-javascript/blob/3eec38753d6f56aee57eabc3e419f1541898c5a8/remote.js#L80-L94)function, but this function only requires one parameter: the endpoint. The passed json-object is never used so an error will always occurs.
```javascript
return this._delete(`tables/${table}/rows/bulk`, {
      rows: data
});
```
```javascript
  _delete(endpoint) { ... }
```
## Context (Environment)
I'm trying to work around the problem right now. 
I am currently solving the problem with a forEach() method like this:

```javascript
const arrayIds = [1, 2];
arrayIds.forEach( id => client.deleteItem('table_name', id));
```
Unfortunately, the whole thing doesn't seem to run as well as it should.
Not all data were deleted and i am getting some 404 or 502 errors but i have no connection problems to the server.
Could it be that there are too many calls to the api endpoints and errors occur? 
Does Directus have a limit on requests to the endpoint within a short period of time?

I also tried to add the missing json-object to the "headers" in `deleteBulk()` in various ways but this doesn't worked.

Maybe `deleteBulk()` will fix my problem. 
I hope you can help me and bring out a fix soon.
Thanks!

**Comment by rijkvanzanten** [comment]
Hey @Padle!

In your example:

```js
var arrayIds = []; 
client.getItems('table_name')
.then( function (entries) {
        entries.data.foreach( function(entry) {
                 arrayIds.push( { "id": entry.id });
        });
});

client.deleteBulk('table_name', arrayIds);
```

`arrayIds` equals an empty array `[]` at the time you try to use `client.deleteBulk`, since `client.getItems` is asynchronous. The error message you got:
```js
{ success: false,
error: { message: 'Rows no specified' },
code: 0,
class: 'Exception',
file: '/var/www/html/directus/api/routes/A1/Entries.php',
line: 64 }
```
is expected to happen, since you send an empty array `[]` to the API.


That being said, your point on the internal `_delete()` method not using the second parameter is totally valid! That was an oversight on my part.. This is the only method that actually sends a body to the delete endpoint, so I must have missed it..


So in conclusion, we both have to tweak some things 😄 

I'll push a fix for the `_delete()` method not using the parameter. Could you in the meantime refactor your logic from
```js
var arrayIds = []; 
client.getItems('table_name')
.then( function (entries) {
        entries.data.foreach( function(entry) {
                 arrayIds.push( { "id": entry.id });
        });
});

client.deleteBulk('table_name', arrayIds);
```

to something like:

```js
// ES5
client.getItems('table_name')
  .then(function (response) {
    return response.data.map(function (entry) {
      return { id: entry.id };
    });
  })
  .then(function (ids) {
    client.deleteItems('table_name');
  });

// ES6
client.getItems('table_name')
   .then(({ data }) => data.map(({ id }) => ({ id })))
   .then(ids => client.deleteBulk(ids));
``` 

_Note: don't forget to write a `catch` for the Promises as well!_

I'll post back here when it's uploaded to NPM

**Comment by rijkvanzanten** [comment]
This has been fixed in version `2.6.1` which is the latest release on [npm](https://www.npmjs.com/package/directus-sdk-javascript) as of right now.

Lemme know if this fixes it for you :)

**Comment by Padle** [comment]
Hey @rijkvanzanten 

Thanks for the reply. I have made a mistake in creating the example. Did not thought about it. In my original code is the array in the` .then() `and is filled correctly. There I also have the content of the array displayed in the console to check it. The `catch` already exists. Thanks for tips!

I will check it out!

I have another comment to make, don't know if i have to open a new issu for the the request.
I am also working with the file system. I have to be able to retrieve and delete files via the API. Using Postman it is possible to delete files with a delete request, but not mentioned in the documentation.

Is there the possibility to implement a function for deleting files?
For Example: 

```javascript
 deleteFile(id = requiredParam('id')) {
        return this._delete(`files/${id}`);
  }
```

**Comment by rijkvanzanten** [comment]
It is certainly possible! That's quite a big misser in the api docs btw.. I've created [an issue over at the docs repo](https://github.com/directus/api-docs/issues/14) to get that fixed. As far as I can tell, you're example is exactly what we need. Do you want to do the honors and open a PR, or shall I paste it in and launch it right away? :)

Thanks for the heads up!

**Comment by Padle** [comment]
Thanks! You can paste it in and launch it right away. I am very happy now! :)

**Comment by rijkvanzanten** [comment]
`client.deleteFile()` has been added in `2.7.0` which is the latest release on [npm](https://www.npmjs.com/package/directus-sdk-javascript) as of right now. Thanks for your help 😄
