### ISSUE TITLE
ES6 code in bundle output

### ISSUE THREAD

**Issue by pimmey** [directus/directus-sdk-javascript#32]
I tried using this SDK with Parcel bundler, but somehow it wouldn't compile the code and I ended up with things like this in my build file, even though I have `es2015` babel preset:

```js
class RemoteInstance {
  constructor(options) {
    const {accessToken, url, headers} = options;
...
```

Seems to be working fine with the following: 

```json
"main": "dist/remote.js"
```

Not sure if that's the case though, maybe that's Parcel's fault or something, but still there is no `dist/index.js` file :-)

**Comment by pimmey** [comment]
Nevermind, that doesn't help. Getting

```
Client.js:4 Uncaught TypeError: _directusSdkJavascript.RemoteInstance is not a constructor
```

**Comment by rijkvanzanten** [comment]
Hey @pimmey!

Did you find the solution?

How did you import the remote instance? Let’s get this resolved :)

**Comment by pimmey** [comment]
howdy @rijkvanzanten,

I'm importing it as per docs:

```
import { RemoteInstance } from 'directus-sdk-javascript'

const Client = new RemoteInstance({
  url: 'http://host.com/admin/api/1.1/',
  accessToken: 'xxxxx'
})
```

Everything works great, but my compiled output contains ES6 code :-( and that doesn't work with some older browsers, of course.

Does it require any certain babel preset? My `.babelrc` looks like this now:

```
{
  "presets" : [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [
    "emotion",
    "transform-decorators-legacy",
    "transform-regenerator"
  ]
}
```

**Comment by rijkvanzanten** [comment]
Hmm this sounds like it’s a problem in your builder config.. does it actually transpile node_modules as well? Or just bundle?

**Comment by pimmey** [comment]
@rijkvanzanten yeah it's a pretty huge React app that I am developing with lots of modules and everything seems to transpire just great except for this module 😁 So I'm wondering what makes it special and what needs to be changed. Guess it'll need some more investigation.

**Comment by pimmey** [comment]
@rijkvanzanten I have some other clues!

So I've tried to isolate the problem and create a clean app using [create-react-app](https://github.com/facebook/create-react-app)

When running `yarn build`, I received the following output:

```bash
yarn build
yarn run v1.3.2
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/directus-sdk-javascript/remote.js:4 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

Also, I've checked the majority of the modules being used and they all point to ES5 code, while this SDK is pointing to ES6 code.

Still pretty confused though and not sure what the problem is exactly 😓

**Comment by rijkvanzanten** [comment]
Hmm i suspect it tries to minify es6 code, what uglify isn’t able to do (yet).. 

> Also, I've checked the majority of the modules being used and they all point to ES5 code, while this SDK is pointing to ES6 code

I feel like you’ve found the problem right here. We already bundle / transpile a version for direct browser use. I think the best solution right now would be to also transpile a version for module use _while not bundling the dependencies_. So you don’t end up with duplicate code.

I’m not sure if i can free up some time right away, so a PR is very welcome 😄

**Comment by pimmey** [comment]
Alrighty, I'll try to close that one :-)

**Comment by rijkvanzanten** [comment]
Awesome! If you need any pointers or have any questions, lemme know 😄

Feel free to join [our Slack](https://slack.getdirectus.com) too 👌🏻

**Comment by truefalse10** [comment]
any news on this? I am encountering the same problem, running the bundled code in IE11 gives me a syntax error

**Comment by pimmey** [comment]
No, sorry. I got out of the project that required this, so there was nothing done about it.

**Comment by rijkvanzanten** [comment]
Hey @truefalse10, I've been working on Directus 7 itself for the past few months, so the JS SDK hasn't been updated that much in the meantime. I'll start using Parcel for the next version of the SDK (compatible with Directus 7). I'll happily merge a PR which uses parcel for the current version :)

**Comment by rijkvanzanten** [comment]
Hey all! I figured out a properly working config over on our other standalone package: [`format-title`](https://github.com/directus/format-title). I'll be porting over this config to the next version of the SDK soon!
