### ISSUE TITLE
404 on updateItem

### ISSUE THREAD

**Issue by arblickspule** [directus/directus-sdk-javascript#44]
Hey guys, getting 404 on updateItem.  Tracked it down to the following ternary...

`
    _put(endpoint, data = {}, isAPI = false, params = {}) {
    const headers = this._requestHeaders;
    console.log('isAPI is... ', isAPI ? true : false) // Returning true due to isAPI being a proto-object rather than boolean value...
    const url = isAPI ? this.api : this.url;        // ...and then returns this.api which is missng the api version in the url 'www.example.com/api'`

Hacked to fix for myself by just setting url to this.url which contains the api version as set in the constructor.

`    // TEMP FIX FOR BACKWARD COMPATIBILTY
    let _url = url.replace('/api/1.1', '');
    this.base = _url.replace(/\/+$/, '');
    this.api = this.base + '/api/';
    this.url = this.api + this.version + '/';`

Cheers!

_Using Quasar Framework in Google Chrome_

**Comment by arblickspule** [comment]
I see that this has been addressed before on the _post function.

https://github.com/directus/directus-sdk-javascript/pull/41


Needs doing on _put and _delete too

If/when I figure out this Git thing I may do a pull request thingy.  Or maybe someone would like to do it for me... 😁

**Comment by rijkvanzanten** [comment]
It seems like you figured it out! Thanks 😄 

Closed in https://github.com/directus/directus-sdk-javascript/pull/41
