### ISSUE TITLE
getItems arguments documented improperly

### ISSUE THREAD

**Issue by joshiefishbein** [directus/directus-sdk-javascript#8]
In regards to options, your documentation details that the default for item status is `1`. But this is not the case. When running `client.getItems()` it will return all items, whether they are active or not. I had to pass in options declaring that I wanted `status: 1` only.

In addition to this, it should also be documented that `sort_order` requires the `sort` argument to be filled, even though `id` is documented as the default.

Last comment, `perPage` and `currentPage` are camelCase, but you're using an underscore for `sort_order`? Why is this? Can we pick a convention and stick to it here?

**Comment by WellingGuzman** [comment]
Hey @joshiefishbein,

> When running client.getItems() it will return all items, whether they are active or not.

I will take a look at that issue right now, it should be default to active only.

> In addition to this, it should also be documented that sort_order requires the sort argument to be filled, even though id is documented as the default.

I will also make sure this is fixed, it should always be default to primary key


> Last comment, perPage and currentPage are camelCase, but you're using an underscore for sort_order? Why is this? Can we pick a convention and stick to it here?

That's true and we've been working on it, using a more standard convention, those are legacy parameter that we keep supporting.

---

Which API version are you using?

Thanks I will get back to you as soon as it's fixed.

**Comment by joshiefishbein** [comment]
@WellingGuzman I'm using 1.1.

Thanks for looking into all this.

**Comment by rijkvanzanten** [comment]
@WellingGuzman How are things progressing with these issues? Should we move them to the api-docs / main Directus repo?

**Comment by WellingGuzman** [comment]
We should move the main issue to directus repo, and discuss the default status value.

**Comment by rijkvanzanten** [comment]
I've moved the issues to the correct repo's 👍  I'll close this one
